#---------------------------------------------------------------------------------------------------
# Eigen system using Arnodi
#---------------------------------------------------------------------------------------------------
"""
    kraus(KL, KU, ρ; dir=:r)

Apply a two-sided Kraus-like map to a matrix `ρ`.

Right direction:
    2 --U--⋅
        |  |
        |  ρ
        |  |
    1 --L--⋅

Left direction:
    ⋅--U-- 1
    |  |  
    ρ  |  
    |  |  
    ⋅--L-- 2

Parameters:
- `KL`, `KU`
  Left and right local tensors defining the transfer action.
- `ρ`
  Matrix to which the map is applied.

Keyword arguments:
- `dir=:r`
  Direction of the action. Use `:r` for the right fixed-point equation and `:l`
  for the left one.

Returns:
- The transformed matrix.

Notes:
- This is a low-level building block for fixed-point and transfer-matrix
  computations.
"""
function kraus(
    KL::AbstractArray{<:Number, 3}, KU::AbstractArray{<:Number, 3},
    ρ::AbstractMatrix; dir::Symbol=:r
)
    if dir == :r
        @tensor out[:] := KL[-1, 3, 1] * ρ[1, 2] * KU[-2, 3, 2]
    elseif dir == :l
        @tensor out[:] := KU[1, 3, -1] * ρ[1, 2] * KL[2, 3, -2]
    else
        error("Illegal direction: $dir.")
    end
    out
end
#---------------------------------------------------------------------------------------------------
"""
    kraus_mat(KL, KU; dir=:r)

Matrix representation of the Kraus-like transfer map defined by `KL` and `KU`.

Parameters:
- `KL`, `KU`
  Left and right local tensors defining the map.

Keyword arguments:
- `dir=:r`
  Direction of the action, matching [`kraus`](@ref).

Returns:
- Dense matrix representation of the linear map acting on vectorized matrices.
"""
function kraus_mat(KL::AbstractArray{<:Number, 3}, KU::AbstractArray{<:Number, 3}; dir::Symbol=:r)
    if dir == :r
        @tensor out[:] := KL[-1, 1, -3] * KU[-2, 1, -4]
    elseif dir == :l
        @tensor out[:] := KU[-3, 1, -1] * KL[-4, 1, -2]
    else
        error("Illegal direction: $dir.")
    end
    a, b, c, d = size(out)
    reshape(out, (a*b, c*d))
end
#---------------------------------------------------------------------------------------------------
"""
    krylov_eigen(KL, KU, ρ0=nothing; dir=:r)

Compute the dominant eigenpair of the transfer map defined by `KL` and `KU`.

Parameters:
- `KL`, `KU`
  Left and right local tensors defining the transfer map.
- `ρ0`
  Optional initial guess for the fixed-point matrix.

Keyword arguments:
- `dir=:r`
  Direction of the fixed-point equation.

Returns:
- `(λ, ρ)` where `λ` is the dominant eigenvalue and `ρ` is the corresponding
  eigenmatrix.

Notes:
- Internally this uses `eigsolve` on the vectorized map.
"""
function krylov_eigen(
    KL::AbstractArray{<:Number, 3}, KU::AbstractArray{<:Number, 3}, 
    ρ0::Union{AbstractMatrix, Nothing}=nothing;
    dir::Symbol=:r
)
    n = size(KL, 1)
    f = ρ -> kraus(KL, KU, reshape(ρ, n, n); dir)
    n = size(KL, 1)
    T = promote_type(eltype(KL), eltype(KU))
    v0 = if isnothing(ρ0)
        reshape(diagm(ones(T, n)), n^2)
    else
        reshape(ρ0, n^2)
    end

    vals, vecs = eigsolve(f, v0, 1, :LM; ishermitian=false)
    if real(tr(vecs[1])) < 0
        vals[1], -reshape(vecs[1], n,n)
    else
        vals[1], reshape(vecs[1], n,n)
    end
end
#---------------------------------------------------------------------------------------------------
"""
    steady_mat(K; dir=:r)

Compute the dominant fixed-point matrix of the transfer map generated by `K`.

Parameters:
- `K`
  Local tensor defining the transfer map.

Keyword arguments:
- `dir=:r`
  Direction of the fixed-point equation.

Returns:
- Hermitian matrix representing the dominant fixed point.

Notes:
- For small bond dimensions a dense eigendecomposition is used; otherwise a
  Krylov solve is used.
"""
function steady_mat(K::AbstractArray{<:Number, 3}; dir::Symbol=:r)
    a, b, _ = size(K)
    vec = if b > a || a <= 8
        m = kraus_mat(K, conj(K); dir) 
        _, vecs = eigen(m)
        v = reshape(vecs[:,end], a, a)
        real(tr(v)) < 0 ? -v : v
    else
        krylov_eigen(K, conj(K); dir)[2]
    end
    return Hermitian(vec)
end
#---------------------------------------------------------------------------------------------------
# Random fixed-point matrix.
"""
    fixed_point_mat(K; dir=:r)

Compute a fixed-point matrix starting from a random initial guess.

Parameters:
- `K`
  Local tensor defining the transfer map.

Keyword arguments:
- `dir=:r`
  Direction of the fixed-point equation.

Returns:
- Hermitian matrix approximating the dominant fixed point.

Notes:
- This is primarily useful as a diagnostic or alternative initialization path.
"""
function fixed_point_mat(
    K::AbstractArray{<:Number, 3};
    dir::Symbol=:r
)
    α = size(K, 1)
    ρ0 = rand(ComplexF64, α, α) |> Hermitian |> Array
    _, vec = krylov_eigen(K, conj(K), ρ0;dir)
    vec |> Hermitian
end
